"""Touch — capacitive spiking tactile array (CLAUDE.md §8 M1).

A capacitive tactile cell emits spikes at a rate proportional to local pressure
(and contact velocity), mimicking texture/contact transmission without polling a
global coordinate grid. We model the touch surface as a ``rows x cols`` grid of
cells; a contact at normalized ``(x, y)`` with a given pressure rate-codes into
one or more spikes on the addressed cell. Sub-threshold contact yields nothing.

``TouchEncoder`` is pure numpy/stdlib (unit-testable). A real touchscreen driver
feeds it contact samples via ``encode_contact``; integration with a specific
device is deferred to a later phase.
"""

from __future__ import annotations

import time

from drhm import config
from drhm.sensory.events import EventBus, Modality, SpikeEvent


class TouchEncoder:
    """Map ``(x, y, pressure)`` contact samples to tactile-cell spike trains."""

    def __init__(
        self,
        grid: tuple[int, int] | None = None,
        pressure_threshold: float | None = None,
        max_spikes: int | None = None,
    ) -> None:
        self.grid = grid or config.TOUCH_GRID
        self.pressure_threshold = (
            config.TOUCH_PRESSURE_THRESHOLD
            if pressure_threshold is None
            else pressure_threshold
        )
        self.max_spikes = (
            config.TOUCH_MAX_SPIKES if max_spikes is None else max_spikes
        )
        self._last: tuple[float, float, float] | None = None  # (x, y, t) for velocity

    @property
    def n_channels(self) -> int:
        rows, cols = self.grid
        return rows * cols

    def cell_index(self, x: float, y: float) -> int:
        """Channel index of the cell containing normalized coords ``(x, y)``."""
        rows, cols = self.grid
        col = min(cols - 1, max(0, int(x * cols)))
        row = min(rows - 1, max(0, int(y * rows)))
        return row * cols + col

    def reset(self) -> None:
        self._last = None

    def encode_contact(
        self,
        x: float,
        y: float,
        pressure: float,
        timestamp: float | None = None,
    ) -> list[SpikeEvent]:
        """Return the spikes generated by one contact sample.

        Spike count rate-codes ``pressure`` boosted by contact velocity; payload
        carries the raw pressure. Below threshold, no contact is registered.
        """
        ts = time.monotonic() if timestamp is None else timestamp
        if pressure < self.pressure_threshold:
            self._last = (x, y, ts)
            return []

        velocity = 0.0
        if self._last is not None:
            px, py, pt = self._last
            dt = ts - pt
            if dt > 0:
                velocity = ((x - px) ** 2 + (y - py) ** 2) ** 0.5 / dt
        self._last = (x, y, ts)

        # Rate code: stronger / faster contact -> more spikes, capped.
        intensity = pressure * (1.0 + velocity)
        n_spikes = max(1, min(self.max_spikes, int(intensity / self.pressure_threshold)))
        channel = self.cell_index(x, y)
        return [
            SpikeEvent(ts, Modality.TOUCH, channel, float(pressure), "touch")
            for _ in range(n_spikes)
        ]


class TouchSource:
    """Adapter publishing tactile spikes onto the bus from contact samples."""

    def __init__(self, bus: EventBus, encoder: TouchEncoder | None = None) -> None:
        self.bus = bus
        self.encoder = encoder or TouchEncoder()

    def feed_contact(
        self, x: float, y: float, pressure: float, timestamp: float | None = None
    ) -> list[SpikeEvent]:
        events = self.encoder.encode_contact(x, y, pressure, timestamp)
        for event in events:
            self.bus.publish_nowait(event)
        return events
